#!/usr/bin/env python3
"""Generate an OVERLAY block of mapper sections for cores/nes.

Each boards/*.c (except shared helpers) shares VMA __RAM_EMU_START__ with a
unique LMA in MAPPER_STORE so:
  - ines.o's bmap gets the correct absolute Mapper*_Init addresses (same
    trick as the old monolithic fceumm_mappers.ld overlays);
  - objcopy --only-section can extract mapper_<stem>.bin for mappers.pak;
  - only the largest overlay counts toward memory-region size (OVERLAY).

Requires -Wl,--no-check-sections (already in cores/_template/Makefile)
because the trampoline at payload offset 0 also lives at __RAM_EMU_START__.
"""
from __future__ import annotations

import argparse
from pathlib import Path

IGNORE_PREFIXES = (
    "__",
    "fceu-emu2413",
    "mmc3",
    "latch",
    "vrcirq",
    "eeprom_93C66",
)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--boards-dir", type=Path, required=True)
    p.add_argument("--objects-dir", type=Path, required=True,
                   help="Directory holding the compiled board .o files")
    p.add_argument("--output", type=Path, required=True)
    args = p.parse_args()

    boards = sorted(
        f for f in args.boards_dir.iterdir()
        if f.suffix == ".c" and not any(f.name.startswith(pref) for pref in IGNORE_PREFIXES)
    )

    lines = [
        "/* Auto-generated by scripts/gen_nes_mapper_overlays_ld.py — do not edit. */",
        "/* Included inside nes_core.ld's SECTIONS { } BEFORE .core_entry.",
        " * OVERLAY: shared VMA, only max size counts toward the region. */",
        "",
        "  OVERLAY __RAM_EMU_START__ : AT (0x60000000)",
        "  {",
    ]

    for board in boards:
        stem = board.stem
        sanitized = stem.replace("-", "_")
        obj_rel = f"{args.objects_dir.as_posix()}/{stem}.o"
        # text/rodata/data then bss: Init addresses match a standalone link
        # at RAM_EMU_START; extracted blob includes BSS zeros (runtime also
        # memset-clears the rest of the 48K window).
        lines.append(f"    .overlay_nes_mapper_{sanitized}")
        lines.append("    {")
        lines.append("      . = ALIGN(4);")
        lines.append(f"      {obj_rel} (.text .text* .rodata .rodata* .data .data*)")
        lines.append("      . = ALIGN(4);")
        lines.append(f"      {obj_rel} (.bss .bss* COMMON)")
        lines.append("      . = ALIGN(4);")
        lines.append("    }")

    lines.append("  }")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f'file "{args.output}" generated ({len(boards)} mapper overlay(s))')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
