#!/bin/bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <rom.gba> [loaded_gba_rom.c]"
    exit 1
fi

INFILE=$1
OUTFILE=loaded_gba_rom.c
if [[ $# -gt 1 ]]; then
    OUTFILE=$2
fi

SIZE=$(wc -c < "$INFILE" | tr -d ' ')
SRC_NAME=$(basename "$INFILE")

{
    echo "/* Auto-generated by update_gba_rom.sh from ${SRC_NAME} */"
    echo "const unsigned char gba_embedded_rom[] = {"
    xxd -i < "$INFILE"
    echo "};"
    echo "const unsigned int gba_embedded_rom_size = ${SIZE};"
    echo "const char gba_embedded_rom_source[] = \"${SRC_NAME}\";"
} > "$OUTFILE"

echo "Wrote ${OUTFILE} (${SIZE} bytes from ${INFILE})"
